### ISSUE TITLE
test data is not included with package.

### ISSUE THREAD

**Issue by ryanwild7** [elphick/mass-composition#61]
Test data is not included with package, this will aid in faster trouble shooting.

**Comment by elphick** [comment]
Agree.
While it seems to be best not to include the tests in the package, I'll likely break the example data out so it is accessible, making the examples runnable (as you would expect them to be).

**Comment by elphick** [comment]
The data has been included in the package, but this has caused bloat.
Will create a new package for data with data loading functions.

**Comment by elphick** [comment]
0.1.16 has included a pooch package based downloader so that:
1) package size remains small, and
2) users can seamlessly download and access data to replicate examples
